//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSMvcapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transition
    {
        public int TransactionId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Transition Transition1 { get; set; }
        public virtual Transition Transition2 { get; set; }
    }
}
